version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: albaly-postgres
    restart: always
    environment:
      POSTGRES_USER: albaly_user
      POSTGRES_PASSWORD: albaly_password
      POSTGRES_DB: albaly_insights
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
